### ISSUE TITLE
Discord invite is invalid

### ISSUE THREAD

**Issue by tekumara** [tonbo-io/tonbo#265]
### More details about the bug

Discord invite link in README.md is invalid.

**Comment by clivinn-shla81092** [comment]
Hello, we tried to solve the issue.

This is what we did:

Fixed the invalid Discord invite link in the README.md file by replacing it with a valid, permanent invite link.

You can review changes in this commit: https://github.com/clivinn-shla81092/tonbo-io-tonbo-265/commit/da6ad12a2483e43352eb9148277fb7d21ef0b9ba.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by tekumara** [comment]
Has this been fixed? I'm still seeing an Invalid Invite when clicking the [Community](https://discord.gg/j27XVFVmJM) link.
